#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFrontLeft,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBackLeft,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFrontRight, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorBackRight,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorFlag,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     ,                tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Math.c"
#include "Joystick.c"

task main()
{
	waitForStart();
	StartTask(joystickListener);
	while(true) { continue; }
}
