#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorWheelBackRight, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorWheelFrontRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorWheelBackLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorWheelFrontLeft, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorLiftRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorLiftLeft, tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    servoFlag,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servoAuxLift,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_3,    servoBucketRight,     tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "MotorConfig.h"

#include "Math.c"
#include "JoystickUtil.c"
#include "Joystick.c"
#include "DrivingModes.c"

void config()
{
	MOTOR_CONFIG.lift.left			= motorLiftLeft;
	MOTOR_CONFIG.lift.right			= motorLiftRight;
	MOTOR_CONFIG.lift.auxiliaryLift	= servoAuxLift;
	MOTOR_CONFIG.lift.isEnabled		= true;

	MOTOR_CONFIG.wheels.frontLeft	= motorWheelFrontLeft;
	MOTOR_CONFIG.wheels.frontRight	= motorWheelFrontRight;
	MOTOR_CONFIG.wheels.backLeft	= motorWheelBackLeft;
	MOTOR_CONFIG.wheels.backRight	= motorWheelBackRight;
	MOTOR_CONFIG.wheels.isEnabled	= true;

	MOTOR_CONFIG.flag.id			= servoFlag;
	MOTOR_CONFIG.flag.isEnabled		= true;
	writeDebugStream("Flag ID = ");

	string id = "   ";
	sprintf(id, "%d", MOTOR_CONFIG.flag.id);
	writeDebugStreamLine(id);

	MOTOR_CONFIG.buckets.left		= NO_MOTOR;
	MOTOR_CONFIG.buckets.right		= servoBucketRight;
	MOTOR_CONFIG.buckets.isEnabled  = false;
}

task main()
{
	config();
	waitForStart();
	StartTask(joystickListener);

	while (true);
}
