#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorWheelBackLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorWheelBackRight, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorWheelFrontLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorWheelFrontRight, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorLift,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorFlag,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../include/Includes.h"
#include "MotorConfig.c"

task run()
{
	setWheelPower(100);
    wait1Msec(6500);
    stopWheels();
}
