#pragma once

void SL_InitButtonConfig()
{
    SL_CONFIG_BUTTON(liftUp, SL_JOYSTICK_1, SL_DPAD, SL_DPAD_UP)
    SL_CONFIG_BUTTON(liftDown, SL_JOYSTICK_1, SL_DPAD, SL_DPAD_DOWN)
    SL_CONFIG_BUTTON(flagUp, SL_JOYSTICK_1, SL_BUTTON, SL_BUTTON_Y)
    SL_CONFIG_BUTTON(flagDown, SL_JOYSTICK_1, SL_BUTTON, SL_BUTTON_A)
}
